name: build+tests
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Build Dependencies
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S cmake ninja boost git curl zip unzip tar

      - name: Configure
        run: cmake . -G Ninja -D RUN_COVERAGE:BOOL=ON

      - name: Build
        run: cmake --build . --config Debug

      - name: Test
        run: ctest -j6 -C Debug --output-on-failure

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_args: -r

  # windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Configure
  #       run: cmake .

  #     - name: Build
  #       run: cmake --build . --config Release

  #     - name: Test
  #       run: ctest -j6 -C Release -T test --output-on-failure

  # osx:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Configure
  #       env:
  #         CC: gcc-11
  #         CXX: g++-11
  #       run: cmake .

  #     - name: Build
  #       run: cmake --build . --config Release

  #     - name: Test
  #       run: ctest -j6 -C Release -T test --output-on-failure
