name: build+tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Build Dependencies
        run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S cmake ninja

      - name: Configure
        run: cmake . -G Ninja

      - name: Build
        run: cmake --build . --config Release

      - name: Test
        run: ctest -j5 -T test --output-on-failure

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure
        run: cmake .

      - name: Build
        run: cmake --build . --config Release

      - name: Test
        run: ctest -j5 -C Release -T test --output-on-failure

  osx:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure
        env:
          CC: gcc-11
          CXX: g++-11
        run: cmake .

      - name: Build
        run: cmake --build . --config Release

      - name: Test
        run: ctest -j5 -C Release -T test --output-on-failure
